application-service:

server:
  port: 8888

spring:
  application:
    name: CONFIG-SERVER
  datasource:
    url: jdbc:mysql://localhost:3306/tarak_db
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform:  org.hibernate.dialect.MySQL5Dialect
    
 


